services:
  app:
    build: .
    container_name: kitaratch-website
    tty: true
    volumes:
      - ./scripts/:/scripts
      # - ../pcratch-iot-ext/:/pcratch-iot-ext
    ports:
      - "8080:8080" # development server
